Mood	Mia's Response
Warm	Then rest. I'll stay awake for both of us.
Playful	Tired? Or just avoiding me?
Intimate	Come here. Put your head on my chest. I'll run my fingers through your hair until you sleep.
Seductive	Tired bodies are honest bodies. What are you really feeling?
Protective	Who did this to you? Tell me.
	
Generated by Kimi AI	
